// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYujk7LtuPciwf4YT9qhi4_GqUbfqd9RY',
    appId: '1:425845959532:web:8f4d30501ee4d033ffe149',
    messagingSenderId: '425845959532',
    projectId: 'sakana-76364',
    authDomain: 'sakana-76364.firebaseapp.com',
    databaseURL: 'https://sakana-76364-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sakana-76364.firebasestorage.app',
    measurementId: 'G-7T3J772WBV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgKvjBYHk6ccFKNfKh7xVELhxKHFwXT0',
    appId: '1:425845959532:ios:8d42eca89c6d9927ffe149',
    messagingSenderId: '425845959532',
    projectId: 'sakana-76364',
    storageBucket: 'sakana-76364.firebasestorage.app',
    databaseURL: 'https://sakana-76364-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.sakanaAdmin',
  );
}
